# -*- coding: utf-8 -*-
"""Financial_Scopus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZi55VJ8wwUNZ4bpvwcwYmRe8vfIKi6d
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

import pandas as pd

from google.colab import files
uploaded = files.upload()

raw = pd.read_excel("Master_Financial_Data_c.xlsx", sheet_name="Raw Data")
ratios = pd.read_excel("Master_Financial_Data_c.xlsx", sheet_name="Ratios")

print(raw.head())

# ROE (Individual companies)(manual groupby)
tcs_roe = ratios[ratios['Company']=='TCS']['ROE (%)'].mean()
infosys_roe = ratios[ratios['Company']=='Infosys']['ROE (%)'].mean()
wipro_roe = ratios[ratios['Company']=='Wipro']['ROE (%)'].mean()
hcl_roe = ratios[ratios['Company']=='HCL Technologies']['ROE (%)'].mean()
techm_roe = ratios[ratios['Company']=='Tech Mahindra']['ROE (%)'].mean()

# Net Profit Margin - SAME PATTERN, column name mattum maathrurom
tcs_npm = ratios[ratios['Company']=='TCS']['Net Profit Margin (%)'].mean()
infosys_npm = ratios[ratios['Company']=='Infosys']['Net Profit Margin (%)'].mean()
wipro_npm = ratios[ratios['Company']=='Wipro']['Net Profit Margin (%)'].mean()
hcl_npm = ratios[ratios['Company']=='HCL Technologies']['Net Profit Margin (%)'].mean()
techm_npm = ratios[ratios['Company']=='Tech Mahindra']['Net Profit Margin (%)'].mean()

# ROCE - SAME PATTERN
tcs_roce = ratios[ratios['Company']=='TCS']['ROCE (%)'].mean()
infosys_roce = ratios[ratios['Company']=='Infosys']['ROCE (%)'].mean()
wipro_roce = ratios[ratios['Company']=='Wipro']['ROCE (%)'].mean()
hcl_roce = ratios[ratios['Company']=='HCL Technologies']['ROCE (%)'].mean()
techm_roce = ratios[ratios['Company']=='Tech Mahindra']['ROCE (%)'].mean()

print(f'--- ROE ---')
print(f'TCS: {tcs_roe:.2f}%  Infosys: {infosys_roe:.2f}%  Wipro: {wipro_roe:.2f}%  HCL: {hcl_roe:.2f}%  TechM: {techm_roe:.2f}%')
print(f'--- Net Profit Margin ---')
print(f'TCS: {tcs_npm:.2f}%  Infosys: {infosys_npm:.2f}%  Wipro: {wipro_npm:.2f}%  HCL: {hcl_npm:.2f}%  TechM: {techm_npm:.2f}%')
print(f'--- ROCE ---')
print(f'TCS: {tcs_roce:.2f}%  Infosys: {infosys_roce:.2f}%  Wipro: {wipro_roce:.2f}%  HCL: {hcl_roce:.2f}%  TechM: {techm_roce:.2f}%')

#overalll(using group by)
# All 6 ratios, all 5 companies - combined loop
all_ratio_columns = ['ROE (%)', 'Net Profit Margin (%)', 'ROCE (%)',
                      'Debt-Equity Ratio', 'Current Ratio (approx)', 'Asset Turnover Ratio']

for ratio_name in all_ratio_columns:
    print(f'--- {ratio_name} ---')
    print(ratios.groupby('Company')[ratio_name].mean().round(2))
    print()

# COMPOSITE SCORE - Overall Ranking


#overalll
# All 6 ratios, all 5 companies - combined loop
all_ratio_columns = ['ROE (%)', 'Net Profit Margin (%)', 'ROCE (%)',
                      'Debt-Equity Ratio', 'Current Ratio (approx)', 'Asset Turnover Ratio']

for ratio_name in all_ratio_columns:
    print(f'--- {ratio_name} ---')
    print(ratios.groupby('Company')[ratio_name].mean().round(2))
    print()

# overall ranking

ratio_columns = ['Net Profit Margin (%)', 'ROE (%)', 'ROCE (%)',
                  'Debt-Equity Ratio', 'Current Ratio (approx)', 'Asset Turnover Ratio']

weights = {col: 1/6 for col in ratio_columns}

norm = ratios.copy()
for col in ratio_columns:
    mn, mx = ratios[col].min(), ratios[col].max()
    if col == 'Debt-Equity Ratio':
        norm[col+'_n'] = (mx - ratios[col]) / (mx - mn) * 100
    else:
        norm[col+'_n'] = (ratios[col] - mn) / (mx - mn) * 100

norm['Composite Score'] = sum(norm[col+'_n'] * weights[col] for col in ratio_columns)

ranking = norm.groupby('Company')['Composite Score'].mean().sort_values(ascending=False)
print('=== OVERALL RANKING (Composite Score) ===')
print(ranking.round(2))

print(raw.columns.tolist())

#prediction

print('===PREDICTED NEXT YEAR (FY2026-27) NET PROFIT===')

Predictions = {}
for Company in raw['Company'].unique():
    cdata = raw[raw['Company']==Company].sort_values('Year')
    yrs = cdata['Year'].apply(lambda x: int(x[2:6])).values.reshape(-1,1)
    profit = cdata['Net Profit (Rs Cr)'].values

    model = LinearRegression()
    model.fit(yrs, profit)
    pred = model.predict([[2027]])[0]
    r2 = model.score(yrs, profit)

    Predictions[Company] = pred
    print(f'{Company:20s} predicted: {pred:10,.0f} Cr (R2={r2:.3f})')

print()
print('Note: R2 close to 1 means strong trend fit (reliable prediction).')
print('R2 close to 0 means weak/fluctuating trend (less reliable prediction).')

# CLUSTERING - Performance Groups (K-Means)

print('=== PERFORMANCE CLUSTERING ===')

avg_ratios = ratios.groupby('Company')[ratio_columns].mean()

scaler = StandardScaler()
scaled = scaler.fit_transform(avg_ratios)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(scaled)
avg_ratios['Cluster'] = clusters

cluster_roe = avg_ratios.groupby('Cluster')['ROE (%)'].mean().sort_values(ascending=False)
labels = {cluster_roe.index[0]: 'High Performer',
          cluster_roe.index[1]: 'Medium Performer',
          cluster_roe.index[2]: 'Needs Improvement'}

avg_ratios['Performance Group'] = avg_ratios['Cluster'].map(labels)

print(avg_ratios[['ROE (%)', 'Net Profit Margin (%)', 'Performance Group']].round(2))

#  CHARTS

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Chart 1: Composite Ranking
ranking_sorted = ranking.sort_values()
axes[0].barh(ranking_sorted.index, ranking_sorted.values, color='#2F5496')
axes[0].set_xlabel('Composite Score')
axes[0].set_title('Overall Performance Ranking')

# Chart 2: Predicted Net Profit (FY2026-27)
comp_names = list(Predictions.keys())
pred_vals = list(Predictions.values())
axes[1].bar(comp_names, pred_vals, color='#70AD47')
axes[1].set_ylabel('Predicted Net Profit (Rs Cr)')
axes[1].set_title('FY2026-27 Predicted Net Profit')
axes[1].tick_params(axis='x', rotation=45)

# Chart 3: Clustering (ROE vs Net Profit Margin)
colors = {'High Performer': 'green', 'Medium Performer': 'orange', 'Needs Improvement': 'red'}
for grp in avg_ratios['Performance Group'].unique():
    sub = avg_ratios[avg_ratios['Performance Group'] == grp]
    axes[2].scatter(sub['Net Profit Margin (%)'], sub['ROE (%)'], label=grp, s=150, color=colors[grp])
for idx, row in avg_ratios.iterrows():
    axes[2].annotate(idx, (row['Net Profit Margin (%)'], row['ROE (%)']), fontsize=8, xytext=(5, 5), textcoords='offset points')
axes[2].set_xlabel('Net Profit Margin (%)')
axes[2].set_ylabel('ROE (%)')
axes[2].set_title('Performance Clusters')
axes[2].legend()

plt.tight_layout()
plt.savefig('Final_Charts.png', dpi=150)
plt.show()

print("\nCharts saved as Final_Charts.png")
print("\n=== ANALYSIS COMPLETE ===")